'use strict';function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function _defineProperties(a,b){for(var d=0;d<b.length;d++){var c=b[d];c.enumerable=c.enumerable||!1;c.configurable=!0;"value"in c&&(c.writable=!0);Object.defineProperty(a,c.key,c)}}function _createClass(a,b,d){b&&_defineProperties(a.prototype,b);d&&_defineProperties(a,d);return a}
function _inherits(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&_setPrototypeOf(a,b)}function _getPrototypeOf(a){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)};return _getPrototypeOf(a)}
function _setPrototypeOf(a,b){_setPrototypeOf=Object.setPrototypeOf||function(a,c){a.__proto__=c;return a};return _setPrototypeOf(a,b)}function isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(a){return!1}}
function _construct(a,b,d){_construct=isNativeReflectConstruct()?Reflect.construct:function(c,a,b){var f=[null];f.push.apply(f,a);c=new (Function.bind.apply(c,f));b&&_setPrototypeOf(c,b.prototype);return c};return _construct.apply(null,arguments)}function _isNativeFunction(a){return-1!==Function.toString.call(a).indexOf("[native code]")}
function _wrapNativeSuper(a){var b="function"===typeof Map?new Map:void 0;_wrapNativeSuper=function(a){function c(){return _construct(a,arguments,_getPrototypeOf(this).constructor)}if(null===a||!_isNativeFunction(a))return a;if("function"!==typeof a)throw new TypeError("Super expression must either be null or a function");if("undefined"!==typeof b){if(b.has(a))return b.get(a);b.set(a,c)}c.prototype=Object.create(a.prototype,{constructor:{value:c,enumerable:!1,writable:!0,configurable:!0}});return _setPrototypeOf(c,
a)};return _wrapNativeSuper(a)}function _assertThisInitialized(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function _possibleConstructorReturn(a,b){return!b||"object"!==typeof b&&"function"!==typeof b?_assertThisInitialized(a):b}function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}
function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,d=Array(a.length);b<a.length;b++)d[b]=a[b];return d}}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}
var KeyNode=function(){function a(b){_classCallCheck(this,a);if(null==b)throw Error("Value cannot be undefined or null");for(var d=arguments.length,c=Array(1<d?d-1:0),f=1;f<d;f++)c[f-1]=arguments[f];if(c.some(function(a){return null==a}))throw Error("Alais cannot be undefined or null");this.value=b;this.aliases=c.length?new Set(c):null}_createClass(a,[{key:"setAlias",value:function(a){if(null!=a)return this.aliases||(this.aliases=new Set),_toConsumableArray(this.aliases.add(a))}},{key:"removeAlias",
value:function(a){if(!this.aliases||null==a)return!1;a=this.aliases["delete"](a);this.aliases.size||(this.aliases=null);return a}}]);return a}(),ValueNode=function ValueNode(a){_classCallCheck(this,ValueNode);if(null==a)throw Error("Key cannot be undefined or null");this.value=a},AliasNode=function AliasNode(a,b){_classCallCheck(this,AliasNode);if(null==a)throw Error("Key cannot be undefined or null");if(null==b)throw Error("Value cannot be undefined or null");this.value=b;this.aliasOf=a},AliasMap=
function(){var a=new WeakMap;return function(b){function d(){_classCallCheck(this,d);var c=_possibleConstructorReturn(this,_getPrototypeOf(d).call(this));a.set(_assertThisInitialized(c),0);return c}_inherits(d,b);_createClass(d,[{key:"get",value:function(a){return(a=Map.prototype.get.call(this,a))&&"value"in a?a.value:void 0}},{key:"getKey",value:function(a){var c=Map.prototype.get.call(this,a);if(c)return c instanceof AliasNode?c.aliasOf:c instanceof ValueNode?c.value:a}},{key:"getAliases",value:function(a){a=
this.getKey(a);if(null!=a)return a=Map.prototype.get.call(this,a),a.aliases?_toConsumableArray(a.aliases):null}},{key:"hasAlias",value:function(a,b){b=Map.prototype.get.call(this,b);return b instanceof AliasNode?b.aliasOf===a:!1}},{key:"delete",value:function(c){var b=this;c=this.getKey(c);if(null==c)return!1;var d=Map.prototype.get.call(this,c),g=d.value;(d=d.aliases)&&d.forEach(function(a){Map.prototype["delete"].call(b,a)});Map.prototype["delete"].call(this,g);Map.prototype["delete"].call(this,
c);a.set(this,this.entriesCount-1);return!0}},{key:"deleteAlias",value:function(a,b){a=this.getKey(a);if(null==a||!this.hasAlias(a,b))return!1;Map.prototype.get.call(this,a).removeAlias(b);Map.prototype["delete"].call(this,b);return!0}},{key:"set",value:function(c,b){for(var d=this,g=arguments.length,e=Array(2<g?g-2:0),f=2;f<g;f++)e[f-2]=arguments[f];if(null!=c&&null!=b){if(this.has(b)&&this.getKey(b)!==c)throw Error("Cannot set value. Value is already in the AliasMap.");e=e.filter(function(a){return null!=
a});for(g=0;g<e.length;g+=1)if(this.has(e[g])&&this.getKey(e[g])!==c)throw Error("Cannot rewrite foreign alias.");if(this.has(c)){g=Map.prototype.get.call(this,c);if(!(g instanceof KeyNode))throw Error("Cannot set key. Key must be of KeyNode type.");this.hasAlias(c,b)&&this.deleteAlias(c,b);g.aliases&&(e=new Set(this.getAliases(c).concat(e||[])));this["delete"](c)}Map.prototype.set.call(this,c,_construct(KeyNode,[b].concat(_toConsumableArray(e))));Map.prototype.set.call(this,b,new ValueNode(c));e.forEach(function(a){Map.prototype.set.call(d,
a,new AliasNode(c,b))});a.set(this,this.entriesCount+1);return this}}},{key:"setAlias",value:function(a){for(var b=this,c=arguments.length,d=Array(1<c?c-1:0),e=1;e<c;e++)d[e-1]=arguments[e];if(null!=a&&d.length){var h=this.getKey(a);if(null!=h){var k=Map.prototype.get.call(this,h);d.forEach(function(a){!b.hasAlias(h,a)&&k.setAlias(a)&&Map.prototype.set.call(b,a,new AliasNode(h,k.value))});return this}}}},{key:"clear",value:function(){a.set(this,0);return Map.prototype.clear.call(this)}},{key:"entriesCount",
get:function(){return a.get(this)}}]);return d}(_wrapNativeSuper(Map))}();module.exports=AliasMap
