'use strict';function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function _defineProperties(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}function _createClass(a,b,c){b&&_defineProperties(a.prototype,b);c&&_defineProperties(a,c);return a}
function _inherits(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&_setPrototypeOf(a,b)}function _getPrototypeOf(a){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(b){return b.__proto__||Object.getPrototypeOf(b)};return _getPrototypeOf(a)}
function _setPrototypeOf(a,b){_setPrototypeOf=Object.setPrototypeOf||function(c,d){c.__proto__=d;return c};return _setPrototypeOf(a,b)}function isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(a){return!1}}
function _construct(a,b,c){_construct=isNativeReflectConstruct()?Reflect.construct:function(c,b,a){var d=[null];d.push.apply(d,b);c=new (Function.bind.apply(c,d));a&&_setPrototypeOf(c,a.prototype);return c};return _construct.apply(null,arguments)}function _isNativeFunction(a){return-1!==Function.toString.call(a).indexOf("[native code]")}
function _wrapNativeSuper(a){var b="function"===typeof Map?new Map:void 0;_wrapNativeSuper=function(c){function a(){return _construct(c,arguments,_getPrototypeOf(this).constructor)}if(null===c||!_isNativeFunction(c))return c;if("function"!==typeof c)throw new TypeError("Super expression must either be null or a function");if("undefined"!==typeof b){if(b.has(c))return b.get(c);b.set(c,a)}a.prototype=Object.create(c.prototype,{constructor:{value:a,enumerable:!1,writable:!0,configurable:!0}});return _setPrototypeOf(a,
c)};return _wrapNativeSuper(a)}function _assertThisInitialized(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function _possibleConstructorReturn(a,b){return!b||"object"!==typeof b&&"function"!==typeof b?_assertThisInitialized(a):b}function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}
function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}var id=0;function _classPrivateFieldLooseKey(a){return"__private_"+id++ +"_"+a}
function _classPrivateFieldLooseBase(a,b){if(!Object.prototype.hasOwnProperty.call(a,b))throw new TypeError("attempted to use private field on non-instance");return a}
var KeyNode=function(){function a(b){_classCallCheck(this,a);if(null==b)throw Error("Value cannot be undefined or null");for(var c=arguments.length,d=Array(1<c?c-1:0),g=1;g<c;g++)d[g-1]=arguments[g];if(d.some(function(c){return null==c}))throw Error("Alais cannot be undefined or null");this.value=b;this.aliases=d.length?new Set(d):null}_createClass(a,[{key:"setAlias",value:function(a){if(null!=a)return this.aliases||(this.aliases=new Set),_toConsumableArray(this.aliases.add(a))}},{key:"removeAlias",
value:function(a){if(!this.aliases||null==a)return!1;a=this.aliases["delete"](a);this.aliases.size||(this.aliases=null);return a}}]);return a}(),ValueNode=function ValueNode(a){_classCallCheck(this,ValueNode);if(null==a)throw Error("Key cannot be undefined or null");this.value=a},AliasNode=function AliasNode(a,b){_classCallCheck(this,AliasNode);if(null==a)throw Error("Key cannot be undefined or null");if(null==b)throw Error("Value cannot be undefined or null");this.value=b;this.aliasOf=a},AliasMap=
function(a){function b(){var c;_classCallCheck(this,b);var a=arguments.length;for(var g=Array(a),e=0;e<a;e++)g[e]=arguments[e];a=_possibleConstructorReturn(this,(c=_getPrototypeOf(b)).call.apply(c,[this].concat(g)));Object.defineProperty(_assertThisInitialized(a),_entriesCount,{writable:!0,value:0});return a}_inherits(b,a);_createClass(b,[{key:"get",value:function(c){return(c=Map.prototype.get.call(this,c))&&"value"in c?c.value:void 0}},{key:"getKey",value:function(c){var a=Map.prototype.get.call(this,
c);if(a)return a instanceof AliasNode?a.aliasOf:a instanceof ValueNode?a.value:c}},{key:"getAliases",value:function(c){c=this.getKey(c);if(null!=c)return c=Map.prototype.get.call(this,c),c.aliases?_toConsumableArray(c.aliases):null}},{key:"hasAlias",value:function(c,a){a=Map.prototype.get.call(this,a);return a instanceof AliasNode?a.aliasOf===c:!1}},{key:"delete",value:function(a){var c=this;a=this.getKey(a);if(null==a)return!1;var b=Map.prototype.get.call(this,a),e=b.value;(b=b.aliases)&&b.forEach(function(a){Map.prototype["delete"].call(c,
a)});Map.prototype["delete"].call(this,e);Map.prototype["delete"].call(this,a);--_classPrivateFieldLooseBase(this,_entriesCount)[_entriesCount];return!0}},{key:"deleteAlias",value:function(a,b){a=this.getKey(a);if(null==a||!this.hasAlias(a,b))return!1;Map.prototype.get.call(this,a).removeAlias(b);Map.prototype["delete"].call(this,b);return!0}},{key:"set",value:function(a,b){for(var c=this,e=arguments.length,d=Array(2<e?e-2:0),f=2;f<e;f++)d[f-2]=arguments[f];if(null!=a&&null!=b){if(this.has(b)&&this.getKey(b)!==
a)throw Error("Cannot set value. Value is already in the AliasMap.");d=d.filter(function(a){return null!=a});for(e=0;e<d.length;e+=1)if(this.has(d[e])&&this.getKey(d[e])!==a)throw Error("Cannot rewrite foreign alias.");if(this.has(a)){e=Map.prototype.get.call(this,a);if(!(e instanceof KeyNode))throw Error("Cannot set key. Key must be of KeyNode type.");this.hasAlias(a,b)&&this.deleteAlias(a,b);e.aliases&&(d=new Set(this.getAliases(a).concat(d||[])));this["delete"](a)}Map.prototype.set.call(this,a,
_construct(KeyNode,[b].concat(_toConsumableArray(d))));Map.prototype.set.call(this,b,new ValueNode(a));d.forEach(function(d){Map.prototype.set.call(c,d,new AliasNode(a,b))});_classPrivateFieldLooseBase(this,_entriesCount)[_entriesCount]+=1;return this}}},{key:"setAlias",value:function(a){for(var b=this,c=arguments.length,e=Array(1<c?c-1:0),h=1;h<c;h++)e[h-1]=arguments[h];if(null!=a&&e.length){var f=this.getKey(a);if(null!=f){var k=Map.prototype.get.call(this,f);e.forEach(function(a){!b.hasAlias(f,
a)&&k.setAlias(a)&&Map.prototype.set.call(b,a,new AliasNode(f,k.value))});return this}}}},{key:"clear",value:function(){_classPrivateFieldLooseBase(this,_entriesCount)[_entriesCount]=0;return Map.prototype.clear.call(this)}},{key:"entriesCount",get:function(){return _classPrivateFieldLooseBase(this,_entriesCount)[_entriesCount]}}]);return b}(_wrapNativeSuper(Map)),_entriesCount=_classPrivateFieldLooseKey("entriesCount");module.exports=AliasMap
