'use strict';function _classCallCheck(a,b){if(!(a instanceof b))throw new TypeError("Cannot call a class as a function");}function _defineProperties(a,b){for(var c=0;c<b.length;c++){var d=b[c];d.enumerable=d.enumerable||!1;d.configurable=!0;"value"in d&&(d.writable=!0);Object.defineProperty(a,d.key,d)}}function _createClass(a,b,c){b&&_defineProperties(a.prototype,b);c&&_defineProperties(a,c);return a}
function _inherits(a,b){if("function"!==typeof b&&null!==b)throw new TypeError("Super expression must either be null or a function");a.prototype=Object.create(b&&b.prototype,{constructor:{value:a,writable:!0,configurable:!0}});b&&_setPrototypeOf(a,b)}function _getPrototypeOf(a){_getPrototypeOf=Object.setPrototypeOf?Object.getPrototypeOf:function(a){return a.__proto__||Object.getPrototypeOf(a)};return _getPrototypeOf(a)}
function _setPrototypeOf(a,b){_setPrototypeOf=Object.setPrototypeOf||function(a,d){a.__proto__=d;return a};return _setPrototypeOf(a,b)}function isNativeReflectConstruct(){if("undefined"===typeof Reflect||!Reflect.construct||Reflect.construct.sham)return!1;if("function"===typeof Proxy)return!0;try{return Date.prototype.toString.call(Reflect.construct(Date,[],function(){})),!0}catch(a){return!1}}
function _construct(a,b,c){_construct=isNativeReflectConstruct()?Reflect.construct:function(d,a,b){var c=[null];c.push.apply(c,a);d=new (Function.bind.apply(d,c));b&&_setPrototypeOf(d,b.prototype);return d};return _construct.apply(null,arguments)}function _isNativeFunction(a){return-1!==Function.toString.call(a).indexOf("[native code]")}
function _wrapNativeSuper(a){var b="function"===typeof Map?new Map:void 0;_wrapNativeSuper=function(a){function d(){return _construct(a,arguments,_getPrototypeOf(this).constructor)}if(null===a||!_isNativeFunction(a))return a;if("function"!==typeof a)throw new TypeError("Super expression must either be null or a function");if("undefined"!==typeof b){if(b.has(a))return b.get(a);b.set(a,d)}d.prototype=Object.create(a.prototype,{constructor:{value:d,enumerable:!1,writable:!0,configurable:!0}});return _setPrototypeOf(d,
a)};return _wrapNativeSuper(a)}function _assertThisInitialized(a){if(void 0===a)throw new ReferenceError("this hasn't been initialised - super() hasn't been called");return a}function _possibleConstructorReturn(a,b){return!b||"object"!==typeof b&&"function"!==typeof b?_assertThisInitialized(a):b}function _toConsumableArray(a){return _arrayWithoutHoles(a)||_iterableToArray(a)||_nonIterableSpread()}
function _arrayWithoutHoles(a){if(Array.isArray(a)){for(var b=0,c=Array(a.length);b<a.length;b++)c[b]=a[b];return c}}function _iterableToArray(a){if(Symbol.iterator in Object(a)||"[object Arguments]"===Object.prototype.toString.call(a))return Array.from(a)}function _nonIterableSpread(){throw new TypeError("Invalid attempt to spread non-iterable instance");}
var KeyNode=function(){function a(b){_classCallCheck(this,a);if(null==b)throw Error("Value cannot be undefined or null");for(var c=arguments.length,d=Array(1<c?c-1:0),h=1;h<c;h++)d[h-1]=arguments[h];if(d.some(function(a){return null==a}))throw Error("Alais cannot be undefined or null");this.value=b;this.aliases=d.length?new Set(d):null}_createClass(a,[{key:"setAlias",value:function(a){if(null!=a)return this.aliases||(this.aliases=new Set),_toConsumableArray(this.aliases.add(a))}},{key:"removeAlias",
value:function(a){if(!this.aliases||null==a)return!1;a=this.aliases["delete"](a);this.aliases.size||(this.aliases=null);return a}}],[{key:"name",get:function(){return"KeyNode"}}]);return a}(),ValueNode=function(){function a(b){_classCallCheck(this,a);if(null==b)throw Error("Key cannot be undefined or null");this.value=b}_createClass(a,null,[{key:"name",get:function(){return"ValueNode"}}]);return a}(),AliasNode=function(){function a(b,c){_classCallCheck(this,a);if(null==b)throw Error("Key cannot be undefined or null");
if(null==c)throw Error("Value cannot be undefined or null");this.value=c;this.aliasOf=b}_createClass(a,null,[{key:"name",get:function(){return"AliasNode"}}]);return a}(),AliasMap=function(){var a=new WeakMap;return function(b){function c(){_classCallCheck(this,c);var d=_possibleConstructorReturn(this,_getPrototypeOf(c).call(this));a.set(_assertThisInitialized(d),0);return d}_inherits(c,b);_createClass(c,[{key:"get",value:function(a){return(a=Map.prototype.get.call(this,a))&&"value"in a?a.value:void 0}},
{key:"getKey",value:function(a){var d=Map.prototype.get.call(this,a);if(d)return d instanceof AliasNode?d.aliasOf:d instanceof ValueNode?d.value:a}},{key:"getAliases",value:function(a){a=this.getKey(a);if(null!=a)return a=Map.prototype.get.call(this,a),a.aliases?_toConsumableArray(a.aliases):null}},{key:"hasAlias",value:function(a,b){b=Map.prototype.get.call(this,b);return b instanceof AliasNode?b.aliasOf===a:!1}},{key:"delete",value:function(d){var b=this;d=this.getKey(d);if(null==d)return!1;var c=
Map.prototype.get.call(this,d),f=c.value;(c=c.aliases)&&c.forEach(function(a){Map.prototype["delete"].call(b,a)});Map.prototype["delete"].call(this,f);Map.prototype["delete"].call(this,d);a.set(this,this.entriesCount-1);return!0}},{key:"deleteAlias",value:function(a,b){a=this.getKey(a);if(null==a||!this.hasAlias(a,b))return!1;Map.prototype.get.call(this,a).removeAlias(b);Map.prototype["delete"].call(this,b);return!0}},{key:"set",value:function(b,c){for(var d=this,f=arguments.length,e=Array(2<f?f-
2:0),g=2;g<f;g++)e[g-2]=arguments[g];if(null!=b&&null!=c){if(this.has(c)&&this.getKey(c)!==b)throw Error("Cannot set value. Value is already in the AliasMap.");e=e.filter(function(a){return null!=a});for(f=0;f<e.length;f+=1)if(this.has(e[f])&&this.getKey(e[f])!==b)throw Error("Cannot rewrite foreign alias.");if(this.has(b)){f=Map.prototype.get.call(this,b);if(!(f instanceof KeyNode))throw Error("Cannot set key. Key must be of KeyNode type.");this.hasAlias(b,c)&&this.deleteAlias(b,c);f.aliases&&(e=
new Set(this.getAliases(b).concat(e||[])));this["delete"](b)}Map.prototype.set.call(this,b,_construct(KeyNode,[c].concat(_toConsumableArray(e))));Map.prototype.set.call(this,c,new ValueNode(b));e.forEach(function(a){Map.prototype.set.call(d,a,new AliasNode(b,c))});a.set(this,this.entriesCount+1);return this}}},{key:"setAlias",value:function(a){for(var b=this,c=arguments.length,d=Array(1<c?c-1:0),e=1;e<c;e++)d[e-1]=arguments[e];if(null!=a&&d.length){var g=this.getKey(a);if(null!=g){var k=Map.prototype.get.call(this,
g);d.forEach(function(a){!b.hasAlias(g,a)&&k.setAlias(a)&&Map.prototype.set.call(b,a,new AliasNode(g,k.value))});return this}}}},{key:"clear",value:function(){a.set(this,0);return Map.prototype.clear.call(this)}},{key:"entriesCount",get:function(){return a.get(this)}}],[{key:"name",get:function(){return"AliasMap"}}]);return c}(_wrapNativeSuper(Map))}();module.exports=AliasMap
